//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Overwatch.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAlert
    {
        public int id { get; set; }
        public string imageUrl { get; set; }
        public Nullable<System.DateTime> createTimestamp { get; set; }
        public Nullable<int> propertyId { get; set; }
        public int propertyAlertStatusId { get; set; }
        public string predictionJson { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual PropertyAlertStatu PropertyAlertStatus { get; set; }
    }
}
